version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Africa/Dakar'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/apps/api'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Africa/Dakar'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'api'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/apps/admin'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Africa/Dakar'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'admin'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Africa/Dakar'
    labels:
      - 'dependencies'
      - 'ci'
